language: node_js
node_js:
  - 12
cache: yarn
services:
  - redis-server
  - mysql
  - postgresql
  - mongodb
script:
  - cd examples/auth && yarn test
  - cd ../knex && yarn test
  - cd ../nuxt && yarn test
  - cd ../simple && yarn test
  - cd .. && yarn test
after_success:
  - yarn codecov
