language: node_js
node_js:
  - 12
cache: yarn
services:
  - redis-server
  - mysql
  - postgresql
  - mongodb
script:
  - cd examples/auth && yarn test
  - cd examples/knex && yarn test
  - cd examples/nuxt && yarn test
  - cd examples/simple && yarn test
  - yarn test
after_success:
  - yarn codecov
