name: Docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
      - 'packages/**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: build
        run: |
          cd docs
          npm install
          npm run build
          cp ./CNAME ./.vuepress/dist/CNAME
          cp ../README.md ./.vuepress/dist/README.md
          touch ./.vuepress/dist/.nojekyll
          mkdir ./.vuepress/dist/.github
          cp ../.github/FUNDING.yml ./.vuepress/dist/.github/FUNDING.yml
      - name: deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: faasjs/faasjs.github.io
          publish_branch: main
          publish_dir: ./docs/.vuepress/dist
          personal_token: ${{ secrets.FAASJS_TOKEN }}
          exclude_assets: ''
