name: Lint

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
  pull_request:
    paths:
      - 'packages/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
          cache: 'npm'
      - name: Install
        run: |
          npm install -g npm@latest
          npm install
      - name: Run Lint
        run: npm run lint
