name: Unit

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
      - .github/workflows/unit.yml
  pull_request:
    paths:
      - 'packages/**'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
      mysql:
        image: mysql
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: test
          MYSQL_DATABASE: test
          MYSQL_USER: test
          MYSQL_PASSWORD: test
        ports:
          - 3306:3306
      mongo:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
          cache: 'npm'
      - name: Install
        run: |
          npm install -g npm@latest
          npm install
      - name: Prepack
        run: npm run build
      - name: Run Tests
        run: npm run test
      - uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOVTOKEN }}
      - uses: paambaati/codeclimate-action@v3.0.0
        if: ${{ github.event_name == 'push'}}
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
